---
apiVersion: apps/v1
kind: Deploymentcd op
metadata:
  labels:
    app: rawad
  name: rawad
  namespace: rawad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rawad
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rawad
    spec:
      containers:
      - image: quay.io/redhatworkshops/bgd:latest
        name: rawad
        env:
        - name: COLOR
          value: "blue"
        resources: {}
---
